{
 "title": "apis",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(tonstatus_http_api[$__range])) by (service) / sum(count_over_time(tonstatus_http_api[$__range])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service availability",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "tonstatus_http_api", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Indexing latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tonstatus_indexing_latency_bucket{}[$__rate_interval])) by (le, service))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get account balance latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tonstatus_functions_time_bucket{}[$__rate_interval])) by (le, service))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx propagation latency (testnet)",
   "type": "heatmap",
   "description": "Time from tx sent to network until it appeared in the API.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(tonstatus_tx_propagation_latency_seconds_sum[1h])) by (service)/sum(rate(tonstatus_tx_propagation_latency_seconds_count[1h])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}