{
 "title": "DAPPs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "availabilty",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tonstatus_dapp_availability", "legendFormat": "{{dapp}}" }
   ]
  },
  {
   "title": "main page time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tonstatus_dapp_main_page_time_bucket{}[$__rate_interval])) by (le, dapp))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "api latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tonstatus_dapp_functions_time_bucket{}[$__rate_interval])) by (le, dapp))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}