{
 "title": "Wallets",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bbridge availability",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(tonconnect_bridge_availability[$__range])) by (bridge) / sum(count_over_time(tonconnect_bridge_availability[$__range])) by (bridge)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bridge_availability",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "tonconnect_bridge_availability", "legendFormat": "{{bridge}}" }
   ]
  },
  {
   "title": "bridge latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, bridge) (rate(tonconnect_bridge_latency_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bridge reconnects per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(tonconnect_bridge_reconnects[10m])",
     "legendFormat": "{{bridge}}"
    }
   ]
  }
 ]
}