// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// PingReadyGet implements pingReadyGet operation.
//
// GET /ready
func (UnimplementedHandler) PingReadyGet(ctx context.Context) (r PingReadyGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PingReadyHead implements pingReadyHead operation.
//
// HEAD /ready
func (UnimplementedHandler) PingReadyHead(ctx context.Context) (r PingReadyHeadRes, _ error) {
	return r, ht.ErrNotImplemented
}
