// Code generated by ogen, DO NOT EDIT.

package oas

type InternalError struct {
	// Error message.
	Error string `json:"error"`
	// Backend error code.
	Code int `json:"code"`
}

// GetError returns the value of Error.
func (s *InternalError) GetError() string {
	return s.Error
}

// GetCode returns the value of Code.
func (s *InternalError) GetCode() int {
	return s.Code
}

// SetError sets the value of Error.
func (s *InternalError) SetError(val string) {
	s.Error = val
}

// SetCode sets the value of Code.
func (s *InternalError) SetCode(val int) {
	s.Code = val
}

func (*InternalError) pingReadyGetRes()  {}
func (*InternalError) pingReadyHeadRes() {}

// PingReadyGetOK is response for PingReadyGet operation.
type PingReadyGetOK struct{}

func (*PingReadyGetOK) pingReadyGetRes() {}

// PingReadyHeadOK is response for PingReadyHead operation.
type PingReadyHeadOK struct{}

func (*PingReadyHeadOK) pingReadyHeadRes() {}
